segundostotales = int(input('Ingresar el cantidad de segundos a transformar en días, horas, minutos y segundos: '))
dias = int(segundostotales/86400)
segundosrestantes = int(segundostotales-(dias*86400))
horas = int(segundosrestantes/3600)
segundosrestantes = int(segundosrestantes-(horas*3600))
minutos = int(segundosrestantes/60)
segundosrestantes = int(segundosrestantes-(minutos*60))
print(f"Segundo Totales a transformar: {segundostotales}")
print(f"Días: {dias}")
print(f"Horas: {horas}")
print(f"Minutos: {minutos}")
print(f"Segundos: {segundosrestantes}")